apiVersion: v1
kind: Service
metadata:
  name: ngservice
  labels:
    app: nginx-server 
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: nginx-server
    version: v2.0.0