apiVersion: v1
kind: Pod
metadata:
  name: nginxpod
  labels: 
    app: nginx-server
spec:
  containers:
    - name: nginxpod
      image: nginx:1.19.4
      ports:
        - containerPort: 8080
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
          cpu: "100m"
        
        


